//USED GLOBALLY
export const SET_USER = 'SET_USER';

//LOGIN
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const LOGGING_IN = 'LOGGING_IN';

//NEWSFEED
export const SET_POSTINGS = 'SET_POSTINGS';
